CREATE DATABASE SOC;

USE SOC;

CREATE TABLE STUDENT
(
	s_ROLLNO INT NOT NULL,
    s_NAME VARCHAR(30) NOT NULL,
    S_CITY varchar(30) NOT NULL,
    S_CGPA DECIMAL(3,2) NOT NULL
);
    
CREATE TABLE STUDENT1
(
	s_ROLLNO INT UNIQUE,
    s_NAME VARCHAR(30) NOT NULL,
    S_CITY varchar(30) NOT NULL,
    S_CGPA DECIMAL(3,2)
);

CREATE TABLE STUDENT2
(
	s_ROLLNO INT PRIMARY KEY,
    s_NAME VARCHAR(30),
    S_CITY varchar(30),
    S_CGPA DECIMAL(3,2)
);

CREATE TABLE STUDENT3
(
	s_ROLLNO INT,
    s_NAME VARCHAR(30),
    S_CITY varchar(30) DEFAULT 'PUNE',
    S_CGPA DECIMAL(3,2)
);

CREATE TABLE STUDENT4
(
	s_ROLLNO INT,
    s_NAME VARCHAR(30),
    S_CITY varchar(30),
    S_CGPA DECIMAL(3,2) CHECK(S_CGPA>4.5)
);

CREATE TABLE STUDENT5
(
	s_ROLLNO INT AUTO_INCREMENT PRIMARY KEY,
    s_NAME VARCHAR(30),
    S_CITY varchar(30),
    S_CGPA DECIMAL(3,2)
) AUTO_INCREMENT=001;
